<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite name="com.testng.ex.TestWithInvocationCount" tests="5" time="3.053" ignored="0" failures="0" timestamp="14 Jun 2017 08:17:37 GMT" skipped="0" hostname="admin-PC" errors="1">
  <testcase name="test2" time="3.027" classname="com.testng.ex.TestWithInvocationCount">
    <error type="org.testng.internal.thread.ThreadTimeoutException" message="Method com.testng.ex.TestWithInvocationCount.test2() didn&#039;t finish within the time-out 3000">
      <![CDATA[org.testng.internal.thread.ThreadTimeoutException: Method com.testng.ex.TestWithInvocationCount.test2() didn't finish within the time-out 3000
]]>
    </error>
  </testcase> <!-- test2 -->
  <testcase name="test3" time="0.005" classname="com.testng.ex.TestWithInvocationCount"/>
  <testcase name="test1" time="0.001" classname="com.testng.ex.TestWithInvocationCount"/>
  <testcase name="test5" time="0.019" classname="com.testng.ex.TestWithInvocationCount"/>
  <testcase name="test4" time="0.001" classname="com.testng.ex.TestWithInvocationCount"/>
</testsuite> <!-- com.testng.ex.TestWithInvocationCount -->
